#!/usr/bin/env python
"""Generate Pydantic models from OpenResponses OpenAPI specification.

This script downloads the OpenResponses OpenAPI spec, detects changes,
and regenerates Pydantic models when the spec has been updated.

Usage:
    python scripts/generate_types.py [--force] [--check] [--version]

Options:
    --force     Regenerate even if spec hasn't changed
    --check     Check if spec has changed without regenerating (exit 1 if changed)
    --version   Show current spec version and hash, then exit
"""

import argparse
import hashlib
import json
import re
import subprocess
import sys
import urllib.request
from pathlib import Path

OPENRESPONSES_SPEC_URL = (
    "https://raw.githubusercontent.com/openresponses/openresponses/main/public/openapi/openapi.json"
)
PROJECT_ROOT = Path(__file__).parent.parent
SPEC_CACHE_DIR = PROJECT_ROOT / "src" / "openresponses_types" / "_spec_cache"
SPEC_CACHE_FILE = SPEC_CACHE_DIR / "openapi.json"
SPEC_HASH_FILE = SPEC_CACHE_DIR / "openapi.sha256"
SPEC_VERSION_FILE = SPEC_CACHE_DIR / "openapi.version"
OUTPUT_FILE = PROJECT_ROOT / "src" / "openresponses_types" / "types.py"
INIT_FILE = PROJECT_ROOT / "src" / "openresponses_types" / "__init__.py"
PYPROJECT_FILE = PROJECT_ROOT / "pyproject.toml"

# `[project] version = "..."` is the only top-level `version =` key in pyproject.toml;
# anchoring to the line start avoids matching `target-version` / `python_version`.
PACKAGE_VERSION_RE = re.compile(r'^version\s*=\s*"([^"]+)"', re.MULTILINE)
SEMVER_RE = re.compile(r"^(\d+)\.(\d+)\.(\d+)")

GENERATION_HEADER = '''\
"""Auto-generated Pydantic models from OpenResponses OpenAPI specification.

DO NOT EDIT THIS FILE MANUALLY.

This file is generated by: scripts/generate_types.py
Source: {spec_url}
Spec Version: {spec_version}
Spec Hash: {spec_hash}

To regenerate:
    uv run python scripts/generate_types.py --force
"""

'''


def fetch_spec() -> bytes:
    """Fetch the OpenResponses OpenAPI spec from the remote URL."""
    print(f"Fetching OpenAPI spec from {OPENRESPONSES_SPEC_URL}...")
    with urllib.request.urlopen(OPENRESPONSES_SPEC_URL, timeout=30) as response:  # noqa: S310
        return response.read()


def extract_spec_version(content: bytes) -> str:
    """Extract the version from the OpenAPI spec."""
    spec = json.loads(content)
    return spec.get("info", {}).get("version", "0.0.0")


def compute_hash(content: bytes) -> str:
    """Compute SHA-256 hash of content."""
    return hashlib.sha256(content).hexdigest()


def get_cached_hash() -> str | None:
    """Get the previously stored spec hash, if any."""
    if SPEC_HASH_FILE.exists():
        return SPEC_HASH_FILE.read_text().strip()
    return None


def get_cached_version() -> str | None:
    """Get the previously stored spec version, if any."""
    if SPEC_VERSION_FILE.exists():
        return SPEC_VERSION_FILE.read_text().strip()
    return None


def save_spec_cache(content: bytes, spec_hash: str, spec_version: str) -> None:
    """Save the spec, its hash, and version to the cache directory."""
    SPEC_CACHE_DIR.mkdir(parents=True, exist_ok=True)
    SPEC_CACHE_FILE.write_bytes(content)
    SPEC_HASH_FILE.write_text(spec_hash)
    SPEC_VERSION_FILE.write_text(spec_version)


def fix_discriminator_issues() -> None:
    """Remove discriminator annotations that cause Pydantic errors.

    datamodel-codegen generates discriminator annotations with StrEnum types,
    but Pydantic requires Literal types for discriminators. This function
    removes the discriminator annotations to avoid runtime errors.
    """
    print("Fixing discriminator compatibility issues...")

    content = OUTPUT_FILE.read_text()

    # Remove discriminator="..." from Field() calls
    content = re.sub(r',\s*discriminator=["\'][^"\']+["\']', "", content)
    content = re.sub(r'discriminator=["\'][^"\']+["\']\s*,\s*', "", content)

    # Remove standalone Field(discriminator=...) - just the argument
    content = re.sub(r'Field\(discriminator=["\'][^"\']+["\']\)', "Field()", content)

    # Remove Annotated[Type, Field()] -> Type (empty Field is useless)
    content = re.sub(r"Annotated\[([^,\[\]]+(?:\[[^\]]*\])?),\s*Field\(\)\s*\]", r"\1", content)

    OUTPUT_FILE.write_text(content)


def format_output() -> None:
    """Format the generated file with ruff."""
    print("Formatting with ruff...")

    # Fix lint issues (import sorting, trailing newline, etc.)
    fix_cmd = ["ruff", "check", "--fix", str(OUTPUT_FILE)]
    subprocess.run(fix_cmd, capture_output=True, text=True, check=False)

    # Format the file
    format_cmd = ["ruff", "format", str(OUTPUT_FILE)]
    result = subprocess.run(format_cmd, capture_output=True, text=True, check=False)

    if result.returncode != 0:
        print(f"Warning: ruff formatting failed: {result.stderr}", file=sys.stderr)


def generate_models(spec_hash: str, spec_version: str) -> None:
    """Run datamodel-codegen to generate Pydantic models."""
    print("Generating Pydantic models...")

    cmd = [
        "datamodel-codegen",
        "--input",
        str(SPEC_CACHE_FILE),
        "--input-file-type",
        "openapi",
        "--output-model-type",
        "pydantic_v2.BaseModel",
        "--use-annotated",
        "--field-constraints",
        "--target-python-version",
        "3.11",
        "--use-double-quotes",
        "--collapse-root-models",
        "--output",
        str(OUTPUT_FILE),
    ]

    result = subprocess.run(cmd, capture_output=True, text=True, check=False)

    if result.returncode != 0:
        print(f"Error generating models: {result.stderr}", file=sys.stderr)
        sys.exit(1)

    prepend_header(spec_hash, spec_version)
    fix_discriminator_issues()
    format_output()
    update_init_metadata(spec_hash, spec_version)
    print(f"Generated: {OUTPUT_FILE}")


def prepend_header(spec_hash: str, spec_version: str) -> None:
    """Prepend generation header to the output file."""
    content = OUTPUT_FILE.read_text()
    header = GENERATION_HEADER.format(
        spec_url=OPENRESPONSES_SPEC_URL,
        spec_hash=spec_hash,
        spec_version=spec_version,
    )

    lines = content.split("\n")
    filtered_lines = []
    skip_header = True
    for line in lines:
        if skip_header and (line.startswith(("#", '"""')) or not line.strip()):
            if line.startswith('"""'):
                skip_header = False
            continue
        filtered_lines.append(line)

    OUTPUT_FILE.write_text(header + "\n".join(filtered_lines))


def update_init_metadata(spec_hash: str, spec_version: str) -> None:
    """Update the __spec_hash__ and __spec_version__ in __init__.py."""
    if not INIT_FILE.exists():
        return

    content = INIT_FILE.read_text()

    # Update __spec_hash__ if it exists
    if "__spec_hash__" in content:
        content = re.sub(r'__spec_hash__\s*=\s*"[^"]*"', f'__spec_hash__ = "{spec_hash}"', content)

    # Update __spec_version__ if it exists
    if "__spec_version__" in content:
        content = re.sub(r'__spec_version__\s*=\s*"[^"]*"', f'__spec_version__ = "{spec_version}"', content)

    INIT_FILE.write_text(content)


def read_package_version() -> str | None:
    """Read the current package version from pyproject.toml."""
    if not PYPROJECT_FILE.exists():
        return None
    match = PACKAGE_VERSION_RE.search(PYPROJECT_FILE.read_text())
    return match.group(1) if match else None


def suggest_package_version() -> str | None:
    """Suggest the next package version for a release off a regenerated spec.

    The package version is deliberately NOT the spec version. The spec is
    versioned by date (e.g. "2026-04-24"), which is not a valid PEP 440
    version and so cannot be used as a package version at all; the package
    follows semantic versioning instead (see the README).

    A spec update normally just adds types, which the README classifies as a
    minor bump, so that is the default suggestion. It is only a starting
    point: diff the regenerated module against the released one before
    releasing, and escalate to a major bump if anything was removed,
    narrowed, or made required.

    Returns None if the current version cannot be parsed, in which case the
    bump has to be chosen by hand.
    """
    current = read_package_version()
    if current is None:
        return None
    match = SEMVER_RE.match(current)
    if match is None:
        return None
    major, minor = int(match.group(1)), int(match.group(2))
    return f"{major}.{minor + 1}.0"


def print_version_guidance(spec_version: str) -> None:
    """Print the spec version and the suggested next package version."""
    current = read_package_version()
    suggested = suggest_package_version()
    print(f"Spec version: {spec_version} (recorded as __spec_version__, not a package version)")
    print(f"Current package version: {current or 'unknown'}")
    if suggested is None:
        print("Could not parse the current package version; choose the next one by hand (see README).")
        return
    print(f"Suggested next package version: {suggested} (minor bump; see README versioning policy)")
    print("Confirm against the diff first: anything removed, narrowed, or newly required needs a major bump.")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate OpenResponses types from OpenAPI spec")
    parser.add_argument("--force", action="store_true", help="Regenerate even if spec hasn't changed")
    parser.add_argument(
        "--check", action="store_true", help="Check if spec has changed without regenerating (exit 1 if changed)"
    )
    parser.add_argument("--version", action="store_true", help="Show current spec version and hash, then exit")
    args = parser.parse_args()

    if args.version:
        cached_version = get_cached_version()
        cached_hash = get_cached_hash()
        if cached_version and cached_hash:
            print(f"Spec hash: {cached_hash}")
            print_version_guidance(cached_version)
        else:
            print("No spec cached yet. Run without --version to generate.")
        return

    spec_content = fetch_spec()
    current_hash = compute_hash(spec_content)
    current_version = extract_spec_version(spec_content)
    cached_hash = get_cached_hash()
    cached_version = get_cached_version()

    if cached_hash == current_hash and not args.force:
        print(f"OpenResponses spec unchanged (v{current_version}, hash: {current_hash[:12]}...)")
        if args.check:
            sys.exit(0)
        print("Use --force to regenerate anyway.")
        return

    if cached_hash is None:
        print(f"First time generating OpenResponses types (spec v{current_version}).")
    else:
        print("OpenResponses spec has CHANGED!")
        print(f"  Previous: v{cached_version} (hash: {cached_hash[:12]}...)")
        print(f"  Current:  v{current_version} (hash: {current_hash[:12]}...)")

    if args.check:
        print("\nSpec change detected. Run without --check to regenerate.")
        sys.exit(1)

    save_spec_cache(spec_content, current_hash, current_version)
    generate_models(current_hash, current_version)

    print("\nGeneration complete!")
    print_version_guidance(current_version)

    suggested = suggest_package_version()
    if suggested:
        print(
            f"\nTo release: set the version in pyproject.toml and src/openresponses_types/__init__.py "
            f"(keep them in sync), then tag: git tag v{suggested}"
        )


if __name__ == "__main__":
    main()
